version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./app:/src
    ports:
      - "5000:5000"
    environment:
        MYSQL_ROOT_PASSWORD: esto_eS_unA_clAve-de_PruebaSuperSecreta

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: esto_eS_unA_clAve_de-PruebaSuperSecreta

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1