version: '3.1'

services:
  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
        MYSQL_ROOT_PASSWORD: "SuperSecreta130663"
        FLASK_APP: index.py
        FLASK_RUN_HOST: 0.0.0.0
        FLASK_RUN_PORT: 80
        FLASK_ENV: production
    command: ["flask", "run"]

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "SuperSecreta130663"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1