version: '3.1'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./app:/src
    ports:
      - "5000:5000"
    environment:
        FLASK_APP: index.py
        FLASK_RUN_HOST: 0.0.0.0
        MYSQL_ROOT_PASSWORD: notSecureChangeMe
        FLASK_ENV: development
    command: ["flask", "run"]

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1